# main.yml
---
- name: ipify_public_ip
  ipify_facts: api_url=http://api.ipify.org
#
# VPC Security Groups
#
- name: vpc-default security-group
  amazon.aws.ec2_group:
    name: vpc-default
    description: VPC default
    vpc_id: "{{ vpc_id | default(vpc.id) }}"
    rules:
      - proto: all
        from_port: -1
        to_port: -1
        cidr_ip: 0.0.0.0/0

- name: vpc-internal-subnets security-group
  vars:
    json: "{{ ec2_vpc_subnet_info }}"
    query: >-
      subnets[].{
          proto: 'all'
          from_port: '-1'
          to_port: '-1'
          cidr_ip: cidr_block
      }
    rules: "{{ json | json_query(query) }}"
  amazon.aws.ec2_group:
    name: vpc-internal-subnets
    description: Allow VPC subnets internal traffic
    vpc_id: "{{ vpc_id | default(vpc.id) }}"
    rules: "{{ rules }}"

- name: Ansible controller security-group
  amazon.aws.ec2_group:
    name: controller
    description: Ansible controller security group
    vpc_id: "{{ vpc_id | default(vpc.id) }}"
    rules:
      - rule_desc: Ansible Controller
        proto: tcp
        ports: [ 22 ]
        cidr_ip: "{{ ipify_public_ip }}/32"

- name: HTTP security-group
  amazon.aws.ec2_group:
    name: http
    description: HTTP security group
    vpc_id: "{{ vpc_id | default(vpc.id) }}"
    rules:
      - rule_desc: HTTP
        proto: tcp
        ports: [ 80 ]
        cidr_ip: 0.0.0.0/0
      - rule_desc: HTTPS
        proto: tcp
        ports: [ 443 ]
        cidr_ip: 0.0.0.0/0

- name: IMAP+POP3 security-group
  ec2_group:
    name: imap+pop3
    description: IMAP+POP3 security group
    vpc_id: "{{ vpc_id | default(vpc.id) }}"
    rules:
    - rule_desc: POP3
      proto: tcp
      ports: [ 110 ]
      cidr_ip: 0.0.0.0/0
    - rule_desc: IMAP
      proto: tcp
      ports: [ 143 ]
      cidr_ip: 0.0.0.0/0
    - rule_desc: IMAPS
      proto: tcp
      ports: [ 993 ]
      cidr_ip: 0.0.0.0/0
    - rule_desc: POP3S
      proto: tcp
      ports: [ 995 ]
      cidr_ip: 0.0.0.0/0

- name: SMTP security-group
  ec2_group:
    name: smtp
    description: SMTP security group
    vpc_id: "{{ vpc_id | default(vpc.id) }}"
    rules:
    - rule_desc: SMTP
      proto: tcp
      ports: [ 25 ]
      cidr_ip: 0.0.0.0/0
    - rule_desc: MSA
      proto: tcp
      ports: [ 587 ]
      cidr_ip: 0.0.0.0/0

- name: SSH security-group
  amazon.aws.ec2_group:
    name: ssh
    description: SSH security group
    vpc_id: "{{ vpc_id | default(vpc.id) }}"
    rules:
      - rule_desc: SSH
        proto: tcp
        ports: [ 22 ]
        cidr_ip: 0.0.0.0/0
