namespace: ball
name: aws
version: 3.0.0
readme: README.md
authors:
  - Allen D. Ball <ball@hcf.dev>
description: A collection of miscellaneous Ansible roles for AWS.
license_file: LICENSE
tags: []
dependencies: {}
repository: https://github.com/allen-ball/ball-aws-collection.git
build_ignore: []

