# main.yml
---
managed_policies:
  EC2AWSRCPolicy:
    Version: "2012-10-17"
    Statement:
      - Sid: DescribeInstances
        Effect: Allow
        Action:
          - ec2:DescribeInstances
        Resource:
          - '*'
      - Sid: AttachVolumes
        Effect: Allow
        Action:
          - ec2:AttachVolume
        Resource:
          - arn:aws:ec2:*:*:volume/*
          - arn:aws:ec2:*:*:instance/*
      - Sid: CreateAndModifyVolumes
        Effect: Allow
        Action:
          - ec2:CreateTags
          - ec2:CreateVolume
        Resource:
          - arn:aws:ec2:*:*:volume/*
